name: Deploy Docker

on:
  push:
    tags:
      - v*

env:
  DOCKERHUB_URL: ghcr.io/nexys-system/fetch-r/fetchrnode

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 20
      - run: yarn
      - run: yarn test
      - run: yarn build
      - name: Login to DockerHub Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: create docker container
        run: docker build --build-arg GIT_SHA=$GITHUB_SHA --build-arg GIT_VERSION=${GITHUB_REF##*/} --tag $DOCKERHUB_URL:latest --tag $DOCKERHUB_URL:master  --tag $DOCKERHUB_URL:${GITHUB_REF##*/} .
      - name: Push
        run: docker push --all-tags $DOCKERHUB_URL
